In [1]:
import itertools
def selection_probs(mine, hers):
    """
    Return the probability from state (mine, hers)
    to choose [0, 1, 2, 3, 4] of my flavor of gummy
    """
    probs = [0.0] * 5
    for order in itertools.product([0,1], repeat=4):
        p = 1.0
        m, h = mine, hers
        for elem in order:
            if m < 0 or h < 0:
                p = 0.0
                break
            if elem == 0:
                p *= float(m) / float(m + h)
                m -= 1
            else:
                p *= float(h) / float(m + h)
                h -= 1         
        num_mine = 4 - sum(order)
        probs[num_mine] += p
    assert 0.9999 < sum(probs) < 1.0001
    return probs
    

def get_prob(mine, hers):
    """
    Return the probability starting at state (mine, hers)
    to get to eat [0, 1, 2] of my flavor
    """
    prefer = [0.0, 0.0, 0.0]
    s_probs = selection_probs(mine, hers)
    prefer[0] += s_probs[0]
    prefer[1] += s_probs[1]
    prefer[2] += s_probs[2] + s_probs[3] + s_probs[4]
    assert 0.9999 < sum(prefer) < 1.0001
    return prefer
    
def state_visit_probs():
    """
    Return a dictionary with keys (mine, hers)
    with values the probability of arriving at that state
    """
    dp = dict()
    dp[(30, 30)] = 1.0
    levels = [(30,30)]
    for round in range(15):
        next_levels = set()
        for m, h in levels:
            v = dp[(m, h)]
            probs = selection_probs(m, h)
            for i, p in enumerate(probs):
                if p == 0:
                    continue
                nm = m - i
                nh = h - 4 + i
                if (nm, nh) not in dp:
                    dp[(nm, nh)] = 0
                next_levels.add((nm, nh))
                dp[(nm, nh)] += v * p
        levels = next_levels
    return dp
        
    

In [10]:
import numpy as np
dp = state_visit_probs()
probs_per_day = []
for i in range(1, 15):
    total_vits = 60 - i * 4
    total_probs = np.array([0.0,0.0,0.0])
    for k, v in dp.items():
        if sum(k) != total_vits:
            continue
        total_probs += np.array(get_prob(k[0], k[1])) * v
    probs_per_day.append(total_probs)
probs_per_day

[array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319]),
 array([ 0.05619982,  0.24977698,  0.69402319])]

In [5]:
get_prob(2,2)

[0.0, 0.0, 0.9999999999999999]

Boy do I feel dumb....